spring.application.name=home-risk-check

server.port=${SPRING_PORT:8080}
spring.profiles.active=local

# JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 파일 업로드 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# jwt
jwt.private-key=classpath:keys/privatekey.pem
jwt.public-key=classpath:keys/publickey.pem

# 안전 점수 가중치 설정
safetyscore.radius=500.0
safetyscore.hotspot-weight=4.5
safetyscore.density-weight=5.0
safetyscore.police-score=5.0
safetyscore.fire-score=2.0
safetyscore.weights.cctv=0.2
safetyscore.weights.police=0.5
safetyscore.weights.lighting=0.3

spring.data.web.pageable.max-page-size=50
