spring.application.name=home-risk-check

server.port=${SPRING_PORT}
spring.profiles.active=local

# JPA ?? ??
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ?? ??? ??
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB