export const mockBlogPosts = [
    {
        id: 1,
        category: 'question',
        title: '분당구에 바람이 많이 부는 이유가 뭘까요?',
        content: '요즘 특히 바람이 강한데 이유가 궁금합니다.',
        authorNickname: '바람이분당구',
        likes: 12,
        commentCount: 5,
        createdAt: '2026-04-30T10:00:00Z',
    },
    {
        id: 2,
        category: 'damage',
        title: '중고 거래 사기 당했습니다…',
        content: '계좌 이체했는데 연락이 끊겼어요. 어떻게 대응해야 할까요?',
        authorNickname: '피해자1',
        likes: 34,
        commentCount: 18,
        createdAt: '2026-04-29T15:20:00Z',
    },
    {
        id: 3,
        category: 'fraud',
        title: '이 업체 사기 같아요. 조심하세요',
        content: '선입금 요구 후 잠수타는 패턴입니다.',
        authorNickname: '경고자',
        likes: 56,
        commentCount: 22,
        createdAt: '2026-04-29T08:10:00Z',
    },
    {
        id: 4,
        category: 'law',
        title: '사기 신고 절차 아시는 분?',
        content: '경찰 신고부터 민사까지 어떤 순서로 진행해야 하나요?',
        authorNickname: '궁금해요',
        likes: 9,
        commentCount: 7,
        createdAt: '2026-04-28T21:00:00Z',
    },
    {
        id: 5,
        category: 'region',
        title: '정자동 맛집 추천 부탁드려요',
        content: '가성비 좋은 식당 찾고 있습니다.',
        authorNickname: '정자동주민',
        likes: 15,
        commentCount: 10,
        createdAt: '2026-04-28T12:30:00Z',
    },
    {
        id: 6,
        category: 'question',
        title: '카카오맵 API 정확도 어떤가요?',
        content: '네이버맵이랑 비교해서 어떤지 궁금합니다.',
        authorNickname: '개발자지망',
        likes: 7,
        commentCount: 4,
        createdAt: '2026-04-27T18:45:00Z',
    },
    {
        id: 7,
        category: 'damage',
        title: '택배 분실 보상 받으신 분 계신가요?',
        content: '택배가 사라졌는데 보상 절차가 궁금합니다.',
        authorNickname: '분실피해자',
        likes: 11,
        commentCount: 6,
        createdAt: '2026-04-27T09:15:00Z',
    },
    {
        id: 8,
        category: 'fraud',
        title: '이 문자 피싱 맞나요?',
        content: '택배 배송 지연이라고 링크가 왔는데 의심스럽습니다.',
        authorNickname: '조심또조심',
        likes: 42,
        commentCount: 13,
        createdAt: '2026-04-26T22:00:00Z',
    },
    {
        id: 9,
        category: 'region',
        title: '판교 근처 조용한 카페 추천',
        content: '노트북 작업하기 좋은 곳 찾습니다.',
        authorNickname: '카공러',
        likes: 19,
        commentCount: 8,
        createdAt: '2026-04-26T14:40:00Z',
    },
    {
        id: 10,
        category: 'law',
        title: '계약서 없이 거래했는데 법적 대응 가능할까요?',
        content: '증거는 일부 대화 내용뿐입니다.',
        authorNickname: '걱정됨',
        likes: 23,
        commentCount: 11,
        createdAt: '2026-04-25T19:30:00Z',
    },
];